FROM python:3.12-slim-bookworm

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libcairo2 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libgdk-pixbuf-2.0-0 \
        libffi-dev \
        shared-mime-info \
        pandoc \
        fontconfig \
        fonts-wqy-zenhei \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml alembic.ini ./
COPY apps ./apps

RUN pip install --no-cache-dir .

CMD ["arq", "apps.worker.main.WorkerSettings"]
